### ISSUE TITLE
can't read libtool

### ISSUE THREAD

**Issue by saraedum** [conda-forge/autotools_clang_conda-feedstock#15]
Running `patch_libtool` did not work for me since it failed to find `libtool`, see [azure logs](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=411351&view=logs&j=240f1fee-52bc-5498-a14a-8361bde76ba0&t=06d62fd2-ab49-5add-9ee5-83b6882d7d2b&l=1909). Am I supposed to `cd` somewhere before running `patch_libtool`? If so, then this is not clear from the instructions here.

```
++ [[ win-64 == \w\i\n\-\6\4 ]]
++ patch_libtool
++ sed -i.bak s/export_symbols_cmds=/export_symbols_cmds2=/g libtool
sed: can't read libtool: No such file or directory
```

**Comment by h-vetinari** [comment]
Same happening for me in https://github.com/conda-forge/openfst-feedstock/pull/27

**Comment by isuruf** [comment]
Yes, you need to cd into wherever `libtool` is.

**Comment by h-vetinari** [comment]
Taking into account that `run_autotools_clang_conda_build.bat` already sets `PREFIX=%LIBRARY_PREFIX`, libtool [should](https://github.com/regro/libcfgraph/blob/master/artifacts/m2-libtool/conda-forge/win-64/m2-libtool-2.4.6-3.json#L285) be in
``` 
$PREFIX/usr/bin/libtool
```

**Comment by isuruf** [comment]
No, that's not how it works. Please see my comment at https://github.com/conda-forge/autotools_clang_conda-feedstock/pull/16#issuecomment-1086732940

**Comment by h-vetinari** [comment]
> Yes, you need to cd into wherever `libtool` is.

I was just pointing out where `libtool` is going to end up. How does your comment relate to the location of `libtool`?

**Comment by isuruf** [comment]
> Please try a project using this package like mpfr and play around with it to get a feel of how it works.

Do this and I'll anwer your questions later.

**Comment by isuruf** [comment]
You don't need to do this on windows, you can try running `./configure` on unix too and see how the makefile interacts with libtool and where libtool is.

**Comment by isuruf** [comment]
Closing this as `patch_libtool` is meant for autotools projects with `libtool` used.
